spring:
  application:
    name: turtorial

turtorial:
  dev-mode: true
  lessons:
    directory: classpath:/lessons
    environmentScripts:
      enabled: false
    frontmatter:
      validation:
        fail-on-error: true
